action_id: trunk-cache-prune
date: 2023-12-22 19:57:48
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1703275068
full_timestamp:
  nanos: 948044000
  seconds: 1703275068
trunk_version: 1.18.0
