action_id: trunk-upgrade-available
date: 2023-12-28 12:31:59
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1703766719
full_timestamp:
  nanos: 290862000
  seconds: 1703766719
trunk_version: 1.18.0
